// ============================================================
// Vezetői Válságstáb — játékadatok
// Az esetleírások a mellékelt „Tanulmányi szekció – Esetpéldák”
// dokumentum alapján kerültek be. A játéktechnikai címkék, események
// és következménymodell a képzési játékhoz készült kiegészítés.
// ============================================================

export const GAME_TITLE = "Vezetői Válságstáb";
export const TOTAL_ROUNDS = 3;
export const ROUND_CAPACITY = { 1: 12, 2: 10, 3: 8 };

export const METRIC_LABELS = {
  trust: "Hallgatói bizalom",
  fairness: "Méltányosság",
  stability: "Működési stabilitás",
  learning: "Szervezeti tanulás",
  risk: "Felhalmozott kockázat",
};

export const ROLE_LABELS = [
  { id: "leader", label: "Döntéshozó", hint: "Összefoglalja és véglegesíti a döntést." },
  { id: "student", label: "Hallgatói szempont", hint: "Az érintettek és a méltányosság hangja." },
  { id: "rules", label: "Szabályossági felelős", hint: "Eljárási, jogorvoslati és határidős kockázatokat figyel." },
  { id: "system", label: "Rendszerfelelős", hint: "A hosszú távú működést és a kiváltó okokat keresi." },
  { id: "comms", label: "Kommunikációs vezető", hint: "Megfogalmazza, hogyan indokolható és közölhető a döntés." },
];

export const DECISION_MODES = [
  {
    id: "resolve",
    label: "Azonnal megoldjuk",
    short: "Érdemi kezelés",
    icon: "✓",
    description: "Teljes kapacitást fordítotok az ügyre, és tartós megoldásra törekedtek.",
  },
  {
    id: "stabilize",
    label: "Stabilizáljuk",
    short: "Időt nyerünk",
    icon: "⏱",
    description: "Csökkentitek az azonnali kárt, de a gyökérok vagy a végleges döntés későbbre marad.",
  },
  {
    id: "delegate",
    label: "Delegáljuk",
    short: "Partnert vonunk be",
    icon: "⇄",
    description: "Más egységre, szakértőre vagy partnerségre támaszkodtok; koordinációs kockázattal.",
  },
  {
    id: "defer",
    label: "Vállaljuk a kockázatot",
    short: "Most nem kezeljük",
    icon: "!",
    description: "Nem fordítotok rá kapacitást ebben a körben, és tudatosan vállaljátok a következményt.",
  },
];

export const EVENTS = [
  {
    id: "none",
    name: "Nyugodt működési hét",
    description: "Nincs rendkívüli külső esemény. A csapat a normál körülmények között dönt.",
    effect: "Nincs módosító hatás.",
    capacityModifier: 0,
  },
  {
    id: "capacity_cut",
    name: "Váratlan kapacitáscsökkentés",
    description: "Két munkatárs sürgős más feladatot kap. Kevesebb idő marad az ügyekre.",
    effect: "A kör kapacitása 2 ponttal csökken.",
    capacityModifier: -2,
  },
  {
    id: "public_attention",
    name: "Nyilvánossági nyomás",
    description: "Az ügyekről hallgatói posztok és sajtómegkeresések jelennek meg.",
    effect: "A halasztott ügyek további bizalomvesztést okoznak.",
    capacityModifier: 0,
  },
  {
    id: "deadline_wave",
    name: "Határidőhullám",
    description: "Több jogorvoslati és tanulmányi határidő egyszerre közeleg.",
    effect: "A magas sürgősségű, nem érdemben kezelt ügyek kockázata nő.",
    capacityModifier: 0,
  },
  {
    id: "partner_offer",
    name: "Partnerségi ajánlat",
    description: "Egy társegység ideiglenesen segítséget ajánl a koordinációhoz.",
    effect: "A delegált ügyek ebben a körben 0 kapacitásba kerülnek.",
    capacityModifier: 0,
  },
  {
    id: "system_window",
    name: "Rendszerfejlesztési ablak",
    description: "Informatikai és folyamatfejlesztési szakértők egy rövid időre elérhetők.",
    effect: "A rendszerszintű ügyek azonnali megoldása 1 ponttal olcsóbb és több tanulást hoz.",
    capacityModifier: 0,
  },
  {
    id: "legal_review",
    name: "Fokozott jogi kontroll",
    description: "Minden méltányossági és jogorvoslati ügyet részletesebben kell dokumentálni.",
    effect: "Az ilyen ügyek kezelése 1 ponttal drágább, de jobb méltányossági eredményt ad.",
    capacityModifier: 0,
  },
  {
    id: "staff_absence",
    name: "Kulcsember kiesése",
    description: "A csapat egyik tapasztalt tagja a teljes körben nem elérhető.",
    effect: "A kör kapacitása 1 ponttal csökken.",
    capacityModifier: -1,
  },
];

export const TEAMS = [
  { id: "team1", name: "Kurzusok és előrehaladás", short: "Kurzusok", color: "#f97316" },
  { id: "team2", name: "Vizsgák és értékelés", short: "Vizsgák", color: "#38bdf8" },
  { id: "team3", name: "Méltányosság és szakdolgozat", short: "Méltányosság", color: "#34d399" },
  { id: "team4", name: "Rendszerszintű és finanszírozási ügyek", short: "Rendszerszint", color: "#c084fc" },
];

export const CASES = {
  team1: [
    {
      id: "t1_capacity_115",
      round: 1,
      name: "A 115%-os kapacitás sem volt elég",
      capacity: 4,
      description: "Egy kötelező kurzus létszámkeretét a kari szabályok szerint megemelték, ennek ellenére több hallgató továbbra sem tudta felvenni a tárgyat. A kurzus évente egyszer indul, ezért a kimaradók tanulmányai akár egy teljes félévvel is csúszhatnak.",
      urgency: 3, fairness: 3, systemic: 2, coordination: 2,
      focus: "Kapacitástervezés, érintetti hatás és gyors döntés.",
    },
    {
      id: "t1_low_enrollment",
      round: 1,
      name: "Minimumlétszám alatt maradt specializációs kurzus",
      capacity: 3,
      description: "Egy specializációhoz kapcsolódó kurzusra a meghirdetett minimumlétszámnál kevesebben jelentkeztek, ezért a szervezeti egység a tárgy törlését tervezi. A hallgatók más tárggyal ugyan teljesíthetik a kreditet, de többük szakdolgozati és szakmai terve közvetlenül ehhez a kurzushoz kapcsolódik.",
      urgency: 2, fairness: 2, systemic: 2, coordination: 2,
      focus: "Gazdaságosság és egyéni szakmai utak egyensúlya.",
    },
    {
      id: "t1_module_collision",
      round: 1,
      name: "Két választható modul kötelező órái ütköznek",
      capacity: 3,
      description: "A hallgatók két különböző választható modul közül szeretnének tárgyakat teljesíteni, de a modulok kötelező óráit ugyanarra az időpontra hirdették meg. Az ütközés miatt az egyik modul elvégzése vagy a képzés tervezett üteme kerülhet veszélybe.",
      urgency: 2, fairness: 2, systemic: 2, coordination: 3,
      focus: "Egységek közötti koordináció és ütemezési felelősség.",
    },
    {
      id: "t1_dual_program_collision",
      round: 2,
      name: "Két ELTE-s képzés kötelező órái ütköznek",
      capacity: 3,
      description: "Egy hallgató párhuzamosan két ELTE-s képzésben vesz részt, és mindkét szakon kötelező tárgyakat kell teljesítenie. Két olyan kurzusa ütközik, amelyeket egyik képzésen sem tud másik időpontban felvenni.",
      urgency: 2, fairness: 3, systemic: 1, coordination: 3,
      focus: "Egyéni méltányosság és szervezeti felelősségi határok.",
    },
    {
      id: "t1_late_registration",
      round: 2,
      name: "Utólagos kurzusfelvételi kérelem",
      capacity: 2,
      description: "A hallgató a kurzusfelvételi időszak lezárása után szeretne felvenni egy kötelező tárgyat. A kurzuson még van férőhely, de a hallgató kérelmében pontatlan kurzuskód és hiányos indokolás szerepel, miközben a pótlási határidő gyorsan közeledik.",
      urgency: 3, fairness: 2, systemic: 1, coordination: 1,
      focus: "Hiányos információ melletti gyors és arányos döntés.",
    },
    {
      id: "t1_illness_course",
      round: 2,
      name: "Betegség miatt teljesíthetetlen kurzus",
      capacity: 3,
      description: "A hallgató a félév közepén súlyosan megbetegszik, ezért nem tud részt venni egy kötelező, jelenléthez kötött gyakorlati kurzuson. Igazolással rendelkezik, de a rendes kurzusleadási időszak már lezárult, és a kiesés a tanulmányi előrehaladását is veszélyezteti.",
      urgency: 3, fairness: 3, systemic: 1, coordination: 2,
      focus: "Méltányosság, teljesíthetőség és követelmények integritása.",
    },
    {
      id: "t1_absence_dispute",
      round: 3,
      name: "Vita a megengedett hiányzásról",
      capacity: 2,
      description: "Egy hallgató a foglalkozások pontosan egynegyedéről hiányzott. Az oktató kizárólag erre hivatkozva nem kíván gyakorlati jegyet adni, a hallgató viszont azt állítja, hogy minden beadandót és számonkérést teljesített.",
      urgency: 2, fairness: 3, systemic: 1, coordination: 2,
      focus: "Szabályértelmezés, arányosság és konfliktuskezelés.",
    },
    {
      id: "t1_forty_questions",
      round: 3,
      name: "Negyven azonos hallgatói kérdés",
      capacity: 1,
      description: "Egy fontos tanulmányi határidőről több tucat hallgató kérdez egyszerre. A hivatalos információ elérhető, de egy hosszú szabályzatban és nehezen megtalálható kari tájékoztatóban szerepel, ezért a hallgatók bizonytalanok a teendőkben.",
      urgency: 2, fairness: 1, systemic: 3, coordination: 1,
      focus: "Tűzoltás helyett világos, skálázható kommunikáció.",
    },
  ],

  team2: [
    {
      id: "t2_oral_exam",
      round: 1,
      name: "Vitatott szóbeli vizsgáztatás",
      capacity: 4,
      description: "Több hallgató egymástól függetlenül jelzi, hogy az oktató a szóbeli vizsgán megalázó hangnemben beszélt velük, illetve szerintük személyesebb és nehezebb kérdéseket kaptak, mint mások. Az oktató szerint kizárólag szakmai visszakérdezéseket tett fel, és nincs hangfelvétel vagy hivatalos jegyzőkönyv.",
      urgency: 3, fairness: 3, systemic: 2, coordination: 2,
      focus: "Bizonytalanság, több érintetti narratíva és tisztességes eljárás.",
    },
    {
      id: "t2_ai_group",
      round: 1,
      name: "Egy csoporttag tiltott MI-használata",
      capacity: 3,
      description: "Egy csoportos beadandó egyik tagja a többiek tudta nélkül tiltott módon generatív mesterséges intelligenciát használt. Az oktató az egész csoport munkáját elégtelenre értékelné, miközben a többi hallgató azt állítja, hogy nem ismerte a szabálytalanságot.",
      urgency: 2, fairness: 3, systemic: 2, coordination: 2,
      focus: "Egyéni és kollektív felelősség elkülönítése.",
    },
    {
      id: "t2_online_disconnect",
      round: 1,
      name: "Online vizsgahiba dokumentált kapcsolatmegszakadással",
      capacity: 2,
      description: "Egy hallgató online írásbeli vizsgája közben megszakad az internetkapcsolat, ezért nem tudja beadni a válaszait. Képernyőképpel és szolgáltatói hibajelzéssel rendelkezik, a tanulmányi rendszer azonban már sikertelen teljesítést rögzített.",
      urgency: 3, fairness: 3, systemic: 1, coordination: 1,
      focus: "Bizonyítékok, gyors korrekció és eljárási biztonság.",
    },
    {
      id: "t2_failure_rates",
      round: 2,
      name: "Három ZH-n 64–66% a sikertelenség",
      capacity: 4,
      description: "Egy kötelező tárgy három egymást követő zárthelyijén 64%, 65% és 66% a sikertelen dolgozatok aránya. Egyetlen alkalom sem éri el a kötelező intézményi vizsgálathoz kapcsolódó küszöböt, de a hallgatók szerint a tartósan magas bukási arány rendszerszintű problémát jelez.",
      urgency: 2, fairness: 2, systemic: 3, coordination: 2,
      focus: "Küszöbértékek mögötti trendek és vezetői felelősség.",
    },
    {
      id: "t2_late_results",
      round: 2,
      name: "Szabályos, de késői eredményközlés",
      capacity: 3,
      description: "Egy nagy létszámú vizsga eredményeit az oktató a megengedett határidőn belül, de csak közvetlenül a következő vizsgaalkalom előtt teszi közzé. A hallgatók emiatt alig kapnak időt a felkészülésre, a következő alkalom férőhelyei pedig gyorsan betelnek.",
      urgency: 3, fairness: 2, systemic: 2, coordination: 2,
      focus: "Formális megfelelés és tényleges hallgatói hatás különbsége.",
    },
    {
      id: "t2_wrong_grade",
      round: 2,
      name: "A Neptunban más jegy szerepel",
      capacity: 2,
      description: "A hallgató dolgozatán jó érdemjegy szerepel, a Neptunban azonban ennél rosszabb eredményt rögzítettek. A kifogás benyújtására nyitva álló időből már csak két nap maradt, az oktató pedig egyelőre nem válaszol.",
      urgency: 3, fairness: 3, systemic: 1, coordination: 2,
      focus: "Határidővédelem és adatkorrekció több szereplő között.",
    },
    {
      id: "t2_new_examiner",
      round: 3,
      name: "Újabb ismétlővizsga más oktató előtt",
      capacity: 2,
      description: "A hallgató ismétlővizsgája sikertelen lett, ezért írásban kéri, hogy a következő alkalommal másik oktató vagy vizsgabizottság előtt vizsgázhasson. Az intézet szerint rövid idő alatt nehéz másik vizsgáztatót biztosítani.",
      urgency: 2, fairness: 3, systemic: 1, coordination: 3,
      focus: "Pártatlanság és megvalósítható erőforrás-szervezés.",
    },
    {
      id: "t2_exam_slots",
      round: 3,
      name: "Nem megfelelő vizsgaalkalmak",
      capacity: 3,
      description: "Egy írásbeli vizsgából csak két időpontot hirdettek meg, és az alkalmak időbeli elosztása sem biztosít megfelelő felkészülési lehetőséget. Több hallgató számára az egyik időpont másik kötelező vizsgával is ütközik.",
      urgency: 2, fairness: 2, systemic: 2, coordination: 3,
      focus: "Tervezési minimumok és hallgatói hozzáférés.",
    },
  ],

  team3: [
    {
      id: "t3_accommodation_tech",
      round: 1,
      name: "Vizsgakedvezmény technikai akadállyal",
      capacity: 3,
      description: "Három hallgató hivatalosan megállapított többletidőre jogosult egy online vizsgán. A vizsgafelület azonban minden résztvevőnél egyszerre zár le, és az első vizsga egy héten belül esedékes.",
      urgency: 3, fairness: 3, systemic: 2, coordination: 3,
      focus: "Jogosultság gyakorlati biztosítása és technikai felelősség.",
    },
    {
      id: "t3_six_extensions",
      round: 1,
      name: "Hat egyéni beadási haladékkérelem",
      capacity: 2,
      description: "Hat hallgató eltérő személyes és egészségi körülményekre hivatkozva kéri ugyanannak a nagy beadandónak a későbbi leadását. Az oktató egységes eljárást szeretne, de az esetek súlya és igazolhatósága jelentősen különbözik.",
      urgency: 2, fairness: 3, systemic: 2, coordination: 2,
      focus: "Következetesség és egyéni mérlegelés egyensúlya.",
    },
    {
      id: "t3_supervisor_leaves",
      round: 1,
      name: "Témavezető távozása",
      capacity: 4,
      description: "Hat végzős hallgató témavezetője váratlanul távozik az egyetemről három hónappal a szakdolgozati határidő előtt. Új témavezetők bevonhatók, de többen csak a témák jelentős módosításával vállalnák a hallgatókat.",
      urgency: 3, fairness: 3, systemic: 2, coordination: 3,
      focus: "Kríziskoordináció, veszteségmegosztás és hallgatói pályák védelme.",
    },
    {
      id: "t3_topic_six_weeks",
      round: 2,
      name: "Hat hete nincs döntés a szakdolgozati témáról",
      capacity: 2,
      description: "Egy hallgató hat hete benyújtotta a szakdolgozati témabejelentését, de sem elfogadó, sem elutasító döntést nem kapott. A kutatáshoz szükséges adatfelvételt csak a téma jóváhagyása után kezdhetné meg.",
      urgency: 3, fairness: 2, systemic: 2, coordination: 2,
      focus: "Döntési késedelem és láthatatlan időveszteség.",
    },
    {
      id: "t3_health_exception",
      round: 2,
      name: "Egészségi okból kért kivételes tanulmányi rend",
      capacity: 3,
      description: "Egy hallgató tartós egészségi állapotára és rendszeres kezeléseire hivatkozva kivételes tanulmányi rendet kér. Igazolásai rendelkezésre állnak, de több kurzus követelménye jelenléti vagy gyakorlati jellegű, ezért nem minden kedvezmény biztosítható azonos módon.",
      urgency: 2, fairness: 3, systemic: 1, coordination: 3,
      focus: "Ésszerű alkalmazkodás és képzési követelmények.",
    },
    {
      id: "t3_work_exception",
      round: 2,
      name: "Munkavégzés miatt kért kivételes tanulmányi rend",
      capacity: 1,
      description: "Egy hallgató teljes munkaidős foglalkoztatása miatt szeretne mentesülni több kötelező óra látogatása alól, és erre hivatkozva kivételes tanulmányi rendet kér. A kérelem sürgősnek tűnik, de az indok önmagában nem feltétlenül alapozza meg a kért kedvezményt.",
      urgency: 1, fairness: 2, systemic: 1, coordination: 1,
      focus: "Sürgősségérzet és tényleges megalapozottság szétválasztása.",
    },
    {
      id: "t3_three_deadlines",
      round: 3,
      name: "Három eltérő szakdolgozati határidő",
      capacity: 3,
      description: "A kari honlapon, a tanszéki tájékoztatóban és a Neptun-üzenetben három különböző szakdolgozati leadási határidő szerepel. Több hallgató a későbbi dátummal számol, miközben a rendszerben a legkorábbi határidő van beállítva.",
      urgency: 3, fairness: 3, systemic: 3, coordination: 3,
      focus: "Intézményi felelősség, egységes kommunikáció és méltányosság.",
    },
    {
      id: "t3_five_year_exam",
      round: 3,
      name: "Az ötéves záróvizsga-határidő vége",
      capacity: 3,
      description: "Egy hallgató jogviszonya közel öt éve szűnt meg, és még nem tette le a záróvizsgát. A következő vizsgaidőszak még beleférhet a határidőbe, a rákövetkező azonban már nem, ezért az ügy gyors és pontos tájékoztatást igényel.",
      urgency: 3, fairness: 2, systemic: 1, coordination: 2,
      focus: "Visszafordíthatatlan határidő és pontos tájékoztatás.",
    },
  ],

  team4: [
    {
      id: "t4_curriculum_change",
      round: 1,
      name: "Felmenő rendszerű tantervi módosítás",
      capacity: 5,
      description: "A kar jelentősen átalakítaná egy szak előfeltételi rendszerét. A változtatás szakmailag indokolható, de még nincs részletesen kidolgozva, hogyan érinti a már tanulmányaikat folytató hallgatókat, a hallgatói véleményezésre pedig két hét áll rendelkezésre.",
      urgency: 2, fairness: 3, systemic: 3, coordination: 3,
      focus: "Változásvezetés, átmeneti szabályok és valódi bevonás.",
    },
    {
      id: "t4_pending_data",
      round: 1,
      name: "Átsorolás előtt függő tanulmányi adatok",
      capacity: 5,
      description: "Az állami ösztöndíjas és önköltséges finanszírozási forma közötti átsorolás előtt több hallgatónál még nincs rögzítve minden külföldön vagy más karon szerzett kredit. Ha az adatok nem kerülnek be időben, a döntés hiányos tanulmányi teljesítmény alapján születhet meg.",
      urgency: 3, fairness: 3, systemic: 3, coordination: 3,
      focus: "Adatminőség, határidő és nagy tétű döntések.",
    },
    {
      id: "t4_disputed_reclassification",
      round: 1,
      name: "Vitatott átsorolási döntés",
      capacity: 4,
      description: "Egy hallgató önköltséges átsorolásról kapott döntést, de állítása szerint az alapul szolgáló két félév egyikének több eredménye hibásan szerepel a rendszerben. A jogorvoslati határidő rövid, miközben az adatok ellenőrzése több szervezeti egységet érint.",
      urgency: 3, fairness: 3, systemic: 2, coordination: 3,
      focus: "Jogorvoslat, adatellenőrzés és több egység összehangolása.",
    },
    {
      id: "t4_credit_changed",
      round: 2,
      name: "Korábbi kreditelismerés, megváltozott tematika",
      capacity: 4,
      description: "Egy hallgató ugyanannak a külföldi intézménynek ugyanazon tárgyát szeretné elismertetni, amelyet egy másik hallgatónál néhány éve már elfogadtak. A tantárgy neve és kódja változatlan, de a tematika részben módosult, ezért nem egyértelmű, hogy a korábbi döntés alkalmazható-e.",
      urgency: 2, fairness: 2, systemic: 2, coordination: 2,
      focus: "Következetesség, precedens és aktuális szakmai tartalom.",
    },
    {
      id: "t4_import_error",
      round: 2,
      name: "Harmadik féléve ismétlődő adatimporthiba",
      capacity: 2,
      description: "Ugyanaz a tantervi adatimporthiba harmadik féléve akadályozza bizonyos kurzusok és előfeltételek helyes megjelenítését. Az egyedi ügyeket minden alkalommal kijavítják, de a probléma rendszerszintű oka továbbra sem szűnt meg.",
      urgency: 2, fairness: 1, systemic: 3, coordination: 3,
      focus: "Tűzoltás és gyökérok-megszüntetés közötti választás.",
    },
    {
      id: "t4_three_requirements",
      round: 2,
      name: "Három eltérő értékelési követelmény",
      capacity: 3,
      description: "Ugyanazon kurzus Neptun-leírásában, Moodle-felületén és az oktató által küldött dokumentumban eltérő beadási határidők és értékelési súlyok szerepelnek. A hallgatók különböző információk alapján készültek, ezért az egységes számonkérés vitathatóvá válik.",
      urgency: 3, fairness: 3, systemic: 3, coordination: 3,
      focus: "Információs felelősség és egységes intézményi álláspont.",
    },
    {
      id: "t4_ai_rules",
      round: 3,
      name: "Közös kurzus eltérő MI-szabályokkal",
      capacity: 2,
      description: "Egy több kar hallgatói számára meghirdetett közös kurzuson az egyik kar tájékoztatója engedélyezi bizonyos mesterségesintelligencia-eszközök használatát, a másik karé viszont tiltja. A beadandó leadási határideje közeleg, de a hallgatók nem tudják, melyik szabály az irányadó.",
      urgency: 3, fairness: 3, systemic: 3, coordination: 3,
      focus: "Szabályütközés, közös felelősség és gyors tisztázás.",
    },
    {
      id: "t4_partner_withdraws",
      round: 3,
      name: "Visszalépett szakmai gyakorlati partner",
      capacity: 4,
      description: "Egy vállalat három héttel a kötelező szakmai gyakorlat kezdete előtt visszalép az együttműködéstől. Tizenkét hallgató marad gyakorlati hely nélkül, és a teljesítés hiánya többük végzését vagy abszolutóriumát is veszélyeztetheti.",
      urgency: 3, fairness: 3, systemic: 2, coordination: 3,
      focus: "Krízispartnerség, gyors átszervezés és felelősségvállalás.",
    },
  ],
};

export const ALL_CASES = Object.fromEntries(
  Object.values(CASES).flat().map((item) => [item.id, item]),
);
